import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { FormEvent, useEffect, useState } from "react";
import { SiteLayout } from "@/components/site/SiteChrome";
import { establishRecoverySessionFromUrl, updatePassword } from "@/lib/huma-auth";

export const Route = createFileRoute("/reset-password")({ component: ResetPassword, head: () => ({ meta: [{ title: "Reset passphrase — HUMA" }] }) });

function ResetPassword() {
  const navigate = useNavigate();
  const [ready, setReady] = useState(false); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [done, setDone] = useState(false);
  useEffect(() => { void establishRecoverySessionFromUrl().then((session) => { if (!session) setError("Open this page from the recovery link sent by HUMA."); else setReady(true); }).catch((e) => setError(e instanceof Error ? e.message : "This recovery link cannot be used.")); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setError(null); if (password.length < 8) { setError("Choose at least 8 characters."); return; } if (password !== confirm) { setError("The two passphrases do not match."); return; } setLoading(true); try { await updatePassword(password); setDone(true); } catch (e) { setError(e instanceof Error ? e.message : "Your passphrase could not be changed."); } finally { setLoading(false); } }
  return <SiteLayout><section className="min-h-[70vh] px-6 py-24"><div className="mx-auto max-w-lg text-center"><p className="text-[9px] uppercase tracking-[0.4em] text-gold-dust">Recover your place</p><h1 className="mt-6 font-display text-4xl font-light text-ivory md:text-5xl">Choose a new passphrase.</h1><p className="mt-5 text-sm leading-relaxed text-ivory/45">Your gestures remain where you left them. Only the key changes.</p>{done ? <div className="mt-12 rounded-3xl border border-gold-dust/20 p-8"><p className="text-sm text-aurora">Your passphrase has been changed.</p><button onClick={() => void navigate({ to: "/my-huma" })} className="mt-6 rounded-full bg-ivory px-7 py-3 text-[10px] uppercase tracking-[0.28em] text-space-black">Enter My HUMA</button></div> : <form onSubmit={submit} className="mt-12 space-y-7 text-left"><label className="block"><span className="text-[9px] uppercase tracking-[0.28em] text-ivory/35">New passphrase</span><input disabled={!ready} type="password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-3 w-full border-b border-ivory/15 bg-transparent py-3 text-base text-ivory outline-none focus:border-gold-dust" /></label><label className="block"><span className="text-[9px] uppercase tracking-[0.28em] text-ivory/35">Confirm passphrase</span><input disabled={!ready} type="password" minLength={8} required value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-3 w-full border-b border-ivory/15 bg-transparent py-3 text-base text-ivory outline-none focus:border-gold-dust" /></label>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<button disabled={!ready || loading} className="w-full rounded-full bg-ivory px-8 py-4 text-[10px] uppercase tracking-[0.3em] text-space-black disabled:opacity-40">{loading ? "Changing…" : "Change my passphrase"}</button></form>}<Link to="/enter" className="mt-8 inline-block text-[10px] tracking-[0.18em] text-ivory/35">Return to Enter HUMA</Link></div></section></SiteLayout>;
}
