/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FutureRouteImport } from './routes/future'
import { Route as EchoRouteImport } from './routes/echo'
import { Route as ConstellationRouteImport } from './routes/constellation'
import { Route as IndexRouteImport } from './routes/index'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoRoute = EchoRouteImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationRoute = ConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/echo': typeof EchoRoute
  '/future': typeof FutureRoute
  '/legal': typeof LegalRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/echo': typeof EchoRoute
  '/future': typeof FutureRoute
  '/legal': typeof LegalRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constellation': typeof ConstellationRoute
  '/echo': typeof EchoRoute
  '/future': typeof FutureRoute
  '/legal': typeof LegalRoute
  '/offer': typeof OfferRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constellation'
    | '/echo'
    | '/future'
    | '/legal'
    | '/offer'
    | '/privacy'
    | '/pulse'
    | '/sitemap.xml'
    | '/stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constellation'
    | '/echo'
    | '/future'
    | '/legal'
    | '/offer'
    | '/privacy'
    | '/pulse'
    | '/sitemap.xml'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/constellation'
    | '/echo'
    | '/future'
    | '/legal'
    | '/offer'
    | '/privacy'
    | '/pulse'
    | '/sitemap.xml'
    | '/stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstellationRoute: typeof ConstellationRoute
  EchoRoute: typeof EchoRoute
  FutureRoute: typeof FutureRoute
  LegalRoute: typeof LegalRoute
  OfferRoute: typeof OfferRoute
  PrivacyRoute: typeof PrivacyRoute
  PulseRoute: typeof PulseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellation': {
      id: '/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof ConstellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstellationRoute: ConstellationRoute,
  EchoRoute: EchoRoute,
  FutureRoute: FutureRoute,
  LegalRoute: LegalRoute,
  OfferRoute: OfferRoute,
  PrivacyRoute: PrivacyRoute,
  PulseRoute: PulseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
